### ISSUE TITLE
无法使用 umi ui

### ISSUE THREAD

**Issue by jctaoo** [BySlin/umi-plugin-electron-builder#10]
使用 `yarn create @umijs/umi-app` 创建项目
使用 `yarn add umi-plugin-electron-builder --dev` 安装 umi-plugin-electron-builder
使用 `UMI_UI=1 umi dev electron` 启动项目

## 期望:
在无报错的情况下正常运行

## 真实情况:
localhost:3000 的错误如下:
```
TypeError: Cannot read property '_' of undefined
    at _default (/Users/jctaoo/private-work/line_bundle_checker/node_modules/umi-plugin-electron-builder/lib/index.js:39:29)
    at /Users/jctaoo/private-work/line_bundle_checker/node_modules/@umijs/core/lib/Service/Service.js:348:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jctaoo/private-work/line_bundle_checker/node_modules/@umijs/core/lib/Service/Service.js:108:103)
    at _next (/Users/jctaoo/private-work/line_bundle_checker/node_modules/@umijs/core/lib/Service/Service.js:110:194)
    at /Users/jctaoo/private-work/line_bundle_checker/node_modules/@umijs/core/lib/Service/Service.js:110:364
    at new Promise (<anonymous>)
    at /Users/jctaoo/private-work/line_bundle_checker/node_modules/@umijs/core/lib/Service/Service.js:110:97
    at Service.applyAPI (/Users/jctaoo/private-work/line_bundle_checker/node_modules/@umijs/core/lib/Service/Service.js:355:7)
    at /Users/jctaoo/private-work/line_bundle_checker/node_modules/@umijs/core/lib/Service/Service.js:438:20
```

## 环境
os: macOS Catalina 10.15.6 (19G73)
yarn: 1.22.10
umi: 3.33.7

## package.json
```json
{
  "private": true,
  "scripts": {
    "start": "UMI_UI=1 umi dev",
    "build": "umi build",
    "postinstall": "umi generate tmp && electron-builder install-app-deps",
    "prettier": "prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'",
    "test": "umi-test",
    "test:coverage": "umi-test --coverage",
    "postuninstall": "electron-builder install-app-deps",
    "electron:dev": "UMI_UI=1 umi dev electron",
    "electron:build:win": "umi build electron --win",
    "electron:build:mac": "umi build electron --mac",
    "electron:build:linux": "umi build electron --linux"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,less,md,json}": [
      "prettier --write"
    ],
    "*.ts?(x)": [
      "prettier --parser=typescript --write"
    ]
  },
  "dependencies": {
    "@ant-design/pro-layout": "^6.5.0",
    "@umijs/preset-react": "1.x",
    "umi": "^3.3.7"
  },
  "devDependencies": {
    "@types/node": "^12.0.12",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@umijs/preset-ui": "^2.2.9",
    "@umijs/test": "^3.3.7",
    "electron": "^11.2.3",
    "electron-builder": "^22.9.1",
    "electron-webpack": "^2.8.2",
    "electron-webpack-ts": "^4.0.1",
    "lint-staged": "^10.0.7",
    "prettier": "^2.2.0",
    "react": "17.x",
    "react-dom": "17.x",
    "typescript": "^4.1.2",
    "umi-plugin-electron-builder": "^1.0.1",
    "yorkie": "^2.0.0"
  },
  "electronWebpack": {
    "renderer": null
  },
  "name": "electron_builder_app",
  "version": "0.0.1",
  "main": "main.js"
}

```

**Comment by BySlin** [comment]
已修复，更新版本即可
