### ISSUE TITLE
umi热更新babel-loader报错

### ISSUE THREAD

**Issue by hefangxuan** [BySlin/umi-plugin-electron-builder#14]
操作系统
  Mac OS
克隆本仓库运行示例代码

运行正常，随便编辑一处代码保存，热更新就会报错
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                4:32:59 PM

 error  in ./src/pages/index.tsx

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/src/pages/index.tsx: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "main". If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/react-refresh/babel.js")
    at ReactFreshBabelPlugin (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/react-refresh/cjs/react-refresh-babel.development.js:24:13)
    at /Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/babel-loader/node_modules/@babel/core/lib/config/full.js:211:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/babel-loader/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/gensync/index.js:291:5)
    at Function.errback (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/gensync/index.js:113:7)
    at errback (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/babel-loader/node_modules/@babel/core/lib/gensync-utils/async.js:70:18)
    at async (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/gensync/index.js:188:31)
    at onFirstPause (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at cachedFunction (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/babel-loader/node_modules/@babel/core/lib/config/caching.js:68:46)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor (/Users/hefx/Code/Electron/umi-plugin-electron-builder/examples/demo/node_modules/babel-loader/node_modules/@babel/core/lib/config/full.js:247:42)
    at loadPluginDescriptor.next (<anonymous>)

 @ ./src/.umi/core/routes.ts 10:17-41
 @ ./src/.umi/umi.ts
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/.umi/umi.ts

```
请帮助我

**Comment by BySlin** [comment]
关闭fastRefresh

**Comment by hefangxuan** [comment]
@BySlin 谢谢，的确可以了
