### ISSUE TITLE
umi执行umi dev electron后没有生成主进程文件src/main/main.ts

### ISSUE THREAD

**Issue by Ha0ran2001** [BySlin/umi-plugin-electron-builder#25]
Error: Cannot find module './index.ts'
      at webpackMissingModule (F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:96:45)
      at Object.<anonymous> (F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:96:130)
      at __webpack_require__ (F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:21:30)
      at F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:85:18
      at Object.<anonymous> (F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:88:10)
      at Module._compile (internal/modules/cjs/loader.js:1078:30)       
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
      at Module.load (internal/modules/cjs/loader.js:935:32)
      at Module._load (internal/modules/cjs/loader.js:776:14)
      at Function.f._load (electron/js2c/asar_bundle.js:5:12684)

**Comment by BySlin** [comment]
执行 umi electron init 生成主进程文件，描述有点问题，2.0执行umi electron init 生成主进程文件，1.0时是自动生成的
