### ISSUE TITLE
mac上构建报错

### ISSUE THREAD

**Issue by minzhang2** [BySlin/umi-plugin-electron-builder#64]
• cannot move downloaded into final location (another process downloaded faster?)  path=/Users/zhangmin/Library/Caches/electron-builder/wine/wine-4.0.1-mac
                                                                                     tempFile=/Users/zhangmin/Library/Caches/electron-builder/wine/700068228
                                                                                     error=rename /Users/zhangmin/Library/Caches/electron-builder/wine/700068228 /Users/zhangmin/Library/Caches/electron-builder/wine/wine-4.0.1-mac: file exists
  ⨯ cannot execute  cause=context deadline exceeded
                    command=/Users/zhangmin/Library/Caches/electron-builder/wine/wine-4.0.1-mac/bin/wine64 /Users/zhangmin/Library/Caches/electron-builder/winCodeSign/winCodeSign-2.6.0/rcedit-x64.exe /Users/zhangmin/work/code/umi-app/dist_electron/win-arm64-unpacked/electron_builder_app.exe --set-version-string FileDescription electron_builder_app --set-version-string ProductName electron_builder_app --set-version-string LegalCopyright 'Copyright © 2022 electron_builder_app' --set-file-version 0.0.1 --set-product-version 0.0.1.0 --set-version-string InternalName electron_builder_app --set-version-string OriginalFilename ''
                    workingDir=
  • Above command failed, retrying 3 more times
  • building        target=nsis file=dist_electron/electron_builder_app Setup 0.0.1.exe archs=arm64 oneClick=true perMachine=false
  ⨯ Get "https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z": read tcp 192.168.6.240:61867->20.205.243.166:443: read: operation timed out
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:206
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:234
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/download.DownloadArtifact
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:107
github.com/develar/app-builder/pkg/download.ConfigureArtifactCommand.func1
        /Volumes/data/Documents/app-builder/pkg/download/artifactDownloader.go:27
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/proc.go:225
runtime.goexit
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/asm_arm64.s:1130  

/Users/zhangmin/work/code/umi-app/node_modules/builder-util/src/util.ts:250
      reject(new ExecError(command, code, out, errorOut))
             ^
Error: /Users/zhangmin/work/code/umi-app/node_modules/app-builder-bin/mac/app-builder_arm64 exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/zhangmin/work/code/umi-app/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at NsisTarget.buildInstaller (/Users/zhangmin/work/code/umi-app/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:228:29)
    at NsisTarget.finishBuild (/Users/zhangmin/work/code/umi-app/node_modules/app-builder-lib/src/targets/nsis/NsisTarget.ts:131:9)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (/Users/zhangmin/work/code/umi-app/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at Packager.doBuild (/Users/zhangmin/work/code/umi-app/node_modules/app-builder-lib/src/packager.ts:453:5)
    at Object.executeFinally (/Users/zhangmin/work/code/umi-app/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/zhangmin/work/code/umi-app/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/zhangmin/work/code/umi-app/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/zhangmin/work/code/umi-app/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by BySlin** [comment]
配个镜像
