### ISSUE TITLE
仓库里examples下的两个例子build都有问题

### ISSUE THREAD

**Issue by liangskyli** [BySlin/umi-plugin-electron-builder#80]
examples下的两个例子构建electron都报错
例：用examples/demo里的pnpm electron:build:mac 构建

错误信息如下：

```
xxx demo % pnpm electron:build:mac

> electron_builder_app@0.0.1 electron:build:mac /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo
> umi build electron --mac

 WARN  deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
 WARN  deprecated @stylelint/postcss-css-in-js@0.38.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
 WARN  deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
 WARN  deprecated @floating-ui/react-dom-interactions@0.3.1: Package renamed to @floating-ui/react
Packages: -175
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Progress: resolved 1267, reused 1189, downloaded 0, added 0, done

devDependencies:
- @types/node 18.16.3
- @types/react 18.2.0
- @types/react-dom 18.2.1
- electron 24.1.3
- electron-builder 23.6.0
- prettier 2.8.8
- prettier-plugin-organize-imports 3.2.2
- prettier-plugin-packagejson 2.4.3
- typescript 5.0.4
- umi-plugin-electron-builder 4.0.6

Done in 10.4s
info  - [你知道吗？] umi g tsconfig 可一键完成项目的 TypeScript 配置。
info  - Umi v4.0.67
info  - Preparing...

✔ Webpack
  Compiled successfully in 2.80s

info  - Memory Usage: 212.4 MB (RSS: 334.53 MB)
info  - [esbuildHelperChecker] Checking esbuild helpers from your dist files...
info  - [esbuildHelperChecker] No conflicts found.

● Webpack █████████████████████████ cache (99%)  
 shutdown


info  - File sizes after gzip:

  112.96 kB  bundled/umi.js
  667 B      bundled/src__pages__index.async.js
  661 B      bundled/layouts__index.async.js
  553 B      bundled/src__pages__docs.async.js
  100 B      bundled/layouts__index.chunk.css

event - Build index.html
vite v4.4.7 building for production...
✓ 2 modules transformed.
../../dist_electron/electron/main.js  1.00 kB │ gzip: 0.63 kB
✓ built in 221ms
vite v4.4.7 building for production...
✓ 1 modules transformed.
../../dist_electron/electron/preload.js  0.12 kB │ gzip: 0.12 kB
✓ built in 12ms
info  - [plugin: umi-plugin-electron-builder] build electron
  • electron-builder  version=24.6.3 os=22.5.0
  • description is missed in the package.json  appPackageFile=/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/dist_electron/bundled/package.json
  • author is missed in the package.json  appPackageFile=/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/dist_electron/bundled/package.json
  • writing effective config  file=dist_electron/builder-effective-config.yaml
Error: Cannot find module 'dmg-builder'
Require stack:
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/app-builder-lib@24.6.3/node_modules/app-builder-lib/out/macPackager.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/app-builder-lib@24.6.3/node_modules/app-builder-lib/out/packager.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/app-builder-lib@24.6.3/node_modules/app-builder-lib/out/index.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/electron-builder@24.6.3/node_modules/electron-builder/out/builder.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/umi-plugin-electron-builder@4.0.6_@types+node@18.16.3_styled-components@6.0.5_typescript@5.0.4_webpack@5.88.2/node_modules/umi-plugin-electron-builder/lib/index.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/@umijs+core@4.0.67/node_modules/@umijs/core/dist/service/plugin.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/@umijs+core@4.0.67/node_modules/@umijs/core/dist/service/pluginAPI.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/@umijs+core@4.0.67/node_modules/@umijs/core/dist/index.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/umi@4.0.67_@babel+core@7.22.9_@types+node@18.16.3_@types+react@18.2.0_eslint@8.46.0_postcss@8_dgce7rg45xpvhyulrafuayvzqq/node_modules/umi/dist/service/service.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/umi@4.0.67_@babel+core@7.22.9_@types+node@18.16.3_@types+react@18.2.0_eslint@8.46.0_postcss@8_dgce7rg45xpvhyulrafuayvzqq/node_modules/umi/dist/cli/cli.js
- /Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/umi@4.0.67_@babel+core@7.22.9_@types+node@18.16.3_@types+react@18.2.0_eslint@8.46.0_postcss@8_dgce7rg45xpvhyulrafuayvzqq/node_modules/umi/bin/umi.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/umi@4.0.67_@babel+core@7.22.9_@types+node@18.16.3_@types+react@18.2.0_eslint@8.46.0_postcss@8_dgce7rg45xpvhyulrafuayvzqq/node_modules/umi/dist/service/requireHook.js:13:26)
    at Function.mod._resolveFilename (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/@umijs+bundler-webpack@4.0.67_styled-components@6.0.5_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/dist/requireHook.js:47:26)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at MacPackager.createTargets (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/app-builder-lib@24.6.3/node_modules/app-builder-lib/src/macPackager.ts:75:33)
    at createTargets (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/app-builder-lib@24.6.3/node_modules/app-builder-lib/src/targets/targetFactory.ts:63:12)
    at Packager.doBuild (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/app-builder-lib@24.6.3/node_modules/app-builder-lib/src/packager.ts:440:41)
    at executeFinally (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/builder-util@24.5.0/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/app-builder-lib@24.6.3/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/app-builder-lib@24.6.3/node_modules/app-builder-lib/src/packager.ts:337:12)
    at executeFinally (/Users/xxxx/project/demo/umi-plugin-electron-builder/examples/demo/node_modules/.pnpm/builder-util@24.5.0/node_modules/builder-util/src/promise.ts:12:14)
 ELIFECYCLE  Command failed with exit code 1.

```

发现构建时会删除安装包

**Comment by liangskyli** [comment]
pnpm: v8.6.9

**Comment by BySlin** [comment]
建议使用yarn，把配置文件.umirc.ts的npmClient也改成yarn

**Comment by liangskyli** [comment]
试了yarn(1.22.4)可以，不能用pnpm，有点坑，希望能解决pnpm的问题，例子里.umirc.ts的npmClient也是配置pnpm

**Comment by liangskyli** [comment]
```
export default defineConfig({
  npmClient: 'pnpm',
  //plugins: ['umi-plugin-electron-builder'],
});
``` 
不用这个plugins, umi build 不会删除安装包，加了这个，就会删除安装包了

**Comment by BySlin** [comment]
这个我解决不了，pnpm最开始的时候是支持的，pnpm后面更新版本就出问题了，我也不知道问题在哪

**Comment by rimsila** [comment]
I used pnpm too but working fine

- Mac m1 ventura
- PNPM 8.6.10
- Node v18.13.0
 "umi-plugin-electron-builder": "^4.0.6",



<img width="1167" alt="Screenshot 2023-07-29 at 11 57 07 PM" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/51617383/6d99a740-00a5-42c2-ba0b-2c7bfb941a1f">

**Comment by liangskyli** [comment]
问题原因：@types/node版本不一致时，这里代码会导致删除安装包
<img width="611" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/31531283/57a07d75-8232-4223-b6f6-772877c7eeda">

**Comment by BySlin** [comment]
这行代码应该只有安装插件的时候执行一次，只是为了保证@types/node的版本和electron的，不一致会导致主进程代码编译报错，npm yarn pnpm我在windows下都能正常运行和打包，我手里没有mac，不保证mac可用性
```
PNPM：8.6.10
NPM：9.6.7
YARN：1.22.19
```
